// ---------------------------------------------------------------------------
// Storage provider types and interfaces
// ---------------------------------------------------------------------------

/** Configuration needed by any storage adapter. */
export interface StorageConfig {
  /** S3-compatible endpoint URL, e.g. http://localhost:9000. */
  readonly endpoint: string;
  /** Bucket name. */
  readonly bucket: string;
  /** Access key identifier. */
  readonly accessKeyId: string;
  /** Secret access key. */
  readonly secretAccessKey: string;
  /** AWS region (may be ignored by local adapters). */
  readonly region?: string;
  /** Whether to use path-style addressing (required for MinIO). */
  readonly forcePathStyle?: boolean;
}

/** Metadata the server records when creating an upload target. */
export interface UploadMetadata {
  /** Expected MIME type or pattern (e.g. "application/pdf"). */
  mimeType?: string;
  /** Maximum allowed file size in bytes. */
  maxSizeBytes?: number;
  /** SHA-256 checksum the client commits to before upload. */
  expectedChecksumSha256?: string;
}

/** Returned to the client so they can upload directly to object storage. */
export interface UploadTarget {
  /** Unique upload identifier generated by the server. */
  readonly uploadId: string;
  /** Pre-signed URL the client PUTs the file to. */
  readonly uploadUrl: string;
  /** When the upload URL expires (RFC 3339). */
  readonly expiresAt: string;
  /** Maximum size in bytes the server will accept. */
  readonly maxSizeBytes: number;
  /** Allowed content types (empty = any). */
  readonly allowedTypes: readonly string[];
}

/** Result after the server confirms an upload completed. */
export interface UploadCompletion {
  /** The server-assigned storage key. */
  readonly objectKey: string;
  /** Actual object size in bytes. */
  readonly size: number;
  /** SHA-256 checksum of the stored object. */
  readonly checksumSha256: string;
  /** Detected MIME type. */
  readonly mimeType: string;
}

/** Pre-signed download URL. */
export interface DownloadUrl {
  /** Pre-signed GET URL. */
  readonly downloadUrl: string;
  /** When the URL expires (RFC 3339). */
  readonly expiresAt: string;
}

// ---------------------------------------------------------------------------
// Storage provider interface
// ---------------------------------------------------------------------------

/**
 * Abstract storage operations.
 *
 * Every implementation MUST:
 * - Prefix all object keys with the workspace ID for tenant isolation.
 * - Generate object keys server-side (the client never chooses a key).
 * - Use short-lived pre-signed URLs so credentials never reach the browser.
 */
export interface StorageProvider {
  /**
   * Creates a pre-signed upload target scoped to a workspace.
   *
   * The server generates a unique `uploadId` and returns a pre-signed PUT
   * URL the client can use to upload the file directly.
   */
  createUploadTarget(workspaceId: string, metadata: UploadMetadata): Promise<UploadTarget>;

  /**
   * Verifies an uploaded object exists and matches the expected metadata.
   *
   * Call after the client confirms they finished uploading. The server
   * performs a `HeadObject` to verify existence, size, and checksum.
   */
  completeUpload(
    workspaceId: string,
    uploadId: string,
    expected?: Pick<UploadMetadata, 'expectedChecksumSha256' | 'maxSizeBytes'>,
  ): Promise<UploadCompletion>;

  /**
   * Creates a short-lived pre-signed download URL for an object.
   */
  createDownloadUrl(workspaceId: string, objectKey: string): Promise<DownloadUrl>;

  /**
   * Deletes an object from storage.
   */
  deleteObject(workspaceId: string, objectKey: string): Promise<void>;
}
